[toolchain]
channel = "nightly-2024-01-15"
profile = "default"
components = [
    "rust-src", "rust-analyzer"

]

# targets = [
#
#     "wasm32-wasi", # for test_wasm.sh
#
#     "wasm32-unknown-unknown", # for repl_wasm
#
# ]
